### ISSUE TITLE
key mapping

### ISSUE THREAD

**Issue by g150446** [TapWithUs/tap-android-sdk#2]
Usually bluetooth keyboards in japan have the key which enable the user to switch between japanese input mode and english input mode. Tap keyboard dose not have this function now. I hope they will enable the function in the future

**Comment by gregory-tapwithus** [comment]
Hi,
We currently don't have built in support for {, } and &.

We plan to add a option for the user to change the mapping and add characters like what you're asking for.
Stay tuned for updates on the [www.tapwithus.com](www.tapwithus.com) website, [tapwithus twitter](https://twitter.com/tapwithus) or [Tappers group on facebook](https://www.facebook.com/groups/TapWithUs/).

**Comment by g150446** [comment]
thank you for reply.i will wait

**Comment by ilouzl** [comment]
@g150446 we believe that our [Mapper tool](https://www.tapwithus.com/mapper/) will allow you doing this. Keep us posted if not.
